version: '3.8'

services:
  # PostgreSQL con TimescaleDB y PostGIS
  timescaledb:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: timescaledb_gis
    environment:
      POSTGRES_DB: gis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      # Configuraciones específicas de TimescaleDB
      TIMESCALEDB_TELEMETRY: "off"
      TS_TUNE_MEMORY: "4GB"
      TS_TUNE_NUM_CPUS: "4"
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./timescale-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/02-gis-init.sql
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama para modelos de IA local
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: serve
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis para cache y colas (opcional)
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana para visualizaciones avanzadas (opcional)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,grafana-clock-panel
    restart: unless-stopped
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
    driver: local
  ollama_data:
    driver: local
  redis_data:
    driver: local
  grafana_data:
    driver: local

networks:
  default:
    name: mcp_network
    driver: bridge